### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by franko108** [aicpp/cloudsync#1]
Hi, scripts are working properly, just one thing isn't clear at the first glance.
For upload, directory in dropbox must exist within defined Dropbox Apps, otherwise it raise Exception:
_Folder listing failed for %s -- assumed empty:_

So, putting this note in your README will make usage more understandable.
All the best,
Frank

**Comment by aicpp** [comment]
Thank you, Frank.  
I [add](https://github.com/aicpp/cloudsync/commit/73aa4e06527ce95223ea673bfab3295f58a01035) note about it.  
So, if you are interested, I already have new modification of this scripts which use config file in json instead command line arguments. I hope, add them in the future.
